import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/layout/header";
import { Toaster } from "react-hot-toast";
import { Footer } from "@/components/layout/footer";
import { AppProvider } from "@/providers";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang } = await params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider locale={lang}>
          <main>
            <NextTopLoader
              color="#ff0042"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl
              showSpinner
              easing="ease"
              speed={600}
              shadow="0 0 10px #ff0042, 0 0 5px #ff0042"
            />
            <Header />
            <div className="container pb-20 md:pb-0">{children}</div>
            <Toaster position="top-center" reverseOrder={false} />
            <Footer />
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
