import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/layout/header";
import { NextIntlClientProvider } from "next-intl";

import { Toaster } from "react-hot-toast";

import "./globals.css";
import { Footer } from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <main>
            <Header />
            <div className="container pb-20 md:pb-0">{children}</div>
            <Toaster position="top-center" reverseOrder={false} />
            <Footer />
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
